### ISSUE TITLE
PHP Dynamic QR Code Updates

### ISSUE THREAD

**Issue by PC-SPEZIALIST** [YunoHost-Apps/qrcode_ynh#2]
Dear @ericgaspar,
thank you so much for packaging this awesome tool.
Do you plan updates or did you run into troubles?

**Comment by ericgaspar** [comment]
I have forgotten about this app... is it working? (It is not in the app catalog)

**Comment by PC-SPEZIALIST** [comment]
> I have forgotten about this app... is it working? (It is not in the app catalog)

The login page loads but the user management seems to be broken.

Login Page
![1](https://github.com/YunoHost-Apps/qrcode_ynh/assets/154607044/d5453c81-b6c1-413b-a16e-1933cfc0f083)
Error Page
![2](https://github.com/YunoHost-Apps/qrcode_ynh/assets/154607044/48837cbd-688f-40e1-b26c-51639414d0cb)

`Fatal error: Uncaught mysqli_sql_exception: Table 'qrcode.qr_users' doesn't exist in /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php:1988 Stack trace: #0 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(1988): mysqli->prepare() #1 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(1594): MysqliDb->_prepareQuery() #2 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(738): MysqliDb->_buildQuery() #3 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(764): MysqliDb->get() #4 /var/www/qrcode/src/authenticate.php(17): MysqliDb->getOne() #5 {main} thrown in /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php on line 1988`

**Comment by ericgaspar** [comment]
did you try to install from the testing branch?

**Comment by PC-SPEZIALIST** [comment]
> did you try to install from the testing branch?

I will try a new installation from the testing branch tomorrow.

**Comment by PC-SPEZIALIST** [comment]
> > did you try to install from the testing branch?
> 
> I will try a new installation from the testing branch tomorrow.

I still see an uncaught mysqli_sql_exception.

`Fatal error: Uncaught mysqli_sql_exception: Table 'qrcode.qr_users' doesn't exist in /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php:1988 Stack trace: #0 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(1988): mysqli->prepare() #1 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(1594): MysqliDb->_prepareQuery() #2 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(738): MysqliDb->_buildQuery() #3 /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php(764): MysqliDb->get() #4 /var/www/qrcode/src/authenticate.php(17): MysqliDb->getOne() #5 {main} thrown in /var/www/qrcode/src/lib/MysqliDb/MysqliDb.php on line 1988`

**Comment by ericgaspar** [comment]
master branch  should be working working out of the box.

**Comment by PC-SPEZIALIST** [comment]
> master branch should be working working out of the box.

You are awesome. It is working now. 👍
